#!/usr/bin/env bash
# Author: rouble matta

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ ! -e /usr/local/incognito.tmp ]; then
    if [ -e /usr/local/bin/isight ]; then 
        #Disable isight
        /usr/local/bin/isight off > /dev/null
    fi 
    #Disable mic
    osascript -e "set volume input volume 0"
    #Disable speakers
    osascript -e "set volume output volume 0"
fi

exit 0
